site_name: Jericho Blog
repo_url: https://github.com/mwwilcox/blog
repo_name: mwwilcox/blog
edit_uri: ""

theme:
  name: 'material'

plugins:
  - blogging:
      dirs:
        - blog
      template: override/custom-blog.html
      categories:
        - name: reviews
          dirs:
            - reviews
    # time_format: '%d/%m/%y %H:%M:%S'
    # meta_time_format: '%Y-%m-%d %H:%M:%S'
    # features:
    #   tags:
    #     index_page: tags.md
    #     insert: top

copyright: Copyright &copy; 2024 Mike Wilcox
