site_name: Jericho Blog
repo_url: https://
plugins:
  - blog:
      format: "(%m/%d/%y)"
      text-align: "right"
    # blog_dir: .
  # - rss:
  #   enabled: !ENV [CI, false]
  #   match_path: blog/posts/.*
  #   date_from_meta:
  #     as_creation: date
  #   categories:
  #     - categories
  #     - tags
  #   # comments_path: "#__comments"
